finish insert and delete sample data
leon123858/ntuaf pull request #55
Opened 2023-02-01 03:22 UTC by dsa66253

2023-02-01 03:46 UTC, leon123858 commented on admin/ntuaf-cli/src/utils/deleteSample.ts
> +async function deleteQueryBatch(db: any, query: any, resolve: any, bar:any) {
好像沒有針對測試資料刪除喔

2023-02-01 03:53 UTC, leon123858 commented
感覺應該沒啥問題, 看你要休息一下,  還是和我直接約個時間確認一下結果, 就可以繼續做

2023-02-01 11:15 UTC, leon123858 commented on admin/ntuaf-cli/src/utils/insertSample.ts
> +				const blockTypeList = Object.keys(BlOCK_TYPE).map((key) => BlOCK_TYPE[key as keyof typeof BlOCK_TYPE])
有 bug:
```ts
const values = Object.values(NumericEnum).filter((v) => !isNaN(Number(v)));
console.log(values); // 👉️ [0, 1, 2]
```
block type 和 item type 抓 key 用上面那行, 因為 ts enum 具有 在 int 具有反身性

2023-02-01 11:16 UTC, leon123858 requested changes

2023-02-01 11:16 UTC, leon123858 commented on admin/ntuaf-cli/src/utils/deleteSample.ts
> +async function deleteQueryBatch(db: any, query: any, resolve: any, bar:any) {
bug

2023-02-01 11:16 UTC, leon123858 commented on admin/ntuaf-cli/src/utils/insertSample.ts
> +				const blockTypeList = Object.keys(BlOCK_TYPE).map((key) => BlOCK_TYPE[key as keyof typeof BlOCK_TYPE])
bug

2023-02-10 13:47 UTC, dsa66253 commented on admin/ntuaf-cli/src/utils/insertSample.ts
> +				const blockTypeList = Object.keys(BlOCK_TYPE).map((key) => BlOCK_TYPE[key as keyof typeof BlOCK_TYPE])
I've fixed the bug. Check that out again.

2023-02-12 14:50 UTC, leon123858 requested changes

2023-02-12 14:50 UTC, leon123858 commented on admin/ntuaf-cli/play.js
> +
語法實驗移掉

2023-02-12 14:50 UTC, leon123858 commented on admin/ntuaf-cli/src/utils/prompts.ts
> +	"refreshCache" = "refreshCache"
用中文吧: 更新系統暫存

2023-02-12 14:50 UTC, leon123858 commented on admin/ntuaf-cli/src/utils/prompts.ts
> +const askEnv = () =>
這兩個方法是不是用不到了?

2023-02-12 14:51 UTC, leon123858 commented
另外, cache 生成的部分, (有空時)進度條加一下, 這倒是不急

2023-02-13 06:35 UTC, dsa66253 commented on admin/ntuaf-cli/play.js
> +
done

2023-02-13 06:35 UTC, dsa66253 commented on admin/ntuaf-cli/src/utils/prompts.ts
> +	"refreshCache" = "refreshCache"
fixed

2023-02-13 06:36 UTC, dsa66253 commented on admin/ntuaf-cli/src/utils/prompts.ts
> +const askEnv = () =>
不知道誒，是不是之後會用到local端資料庫的操作，和真實資料庫的操作？

2023-02-13 07:58 UTC, leon123858 commented on admin/ntuaf-cli/src/utils/prompts.ts
> +const askEnv = () =>
我猜不會, 這不符合習慣, 而且我已經寫好了, 用測試模式開自動連接測試 db, 正式模式開自動連接正式 db
不過之後這塊工作應該會轉交給你, 你可以自己決定

2023-02-14 13:24 UTC, leon123858 approved these changes

2023-02-14 13:24 UTC, leon123858 commented on admin/ntuaf-cli/src/utils/transformData/transformRecommendEvents.ts
> +    const id:string = "always"
bug

2023-02-14 13:24 UTC, leon123858 commented on admin/ntuaf-cli/src/utils/transformData/transformTabEvents.ts
> +                key:FieldValue.arrayUnion({
key 改 data

2023-02-14 16:05 UTC, merged